### ISSUE TITLE
versioning belongs_to associations

### ISSUE THREAD

**Issue by dkharrat** [bdurand/acts_as_revisionable#2]
You mention in your README:

> You can only revision has_many, has_one, and has_and_belongs_to_many associations. You cannot revision belongs_to.

Is there a reason why belongs_to attributes are not versioned? What does it take to support it?

Thanks for creating this awesome gem!

**Comment by bdurand** [comment]
Poor word choice on my part. You can revision the actual relationship since the association column will be stored in the revision. What you can't revision is any changes on the associated record. The reason for this is that by the nature of a belongs_to association, the associated record is a parent record that is presumably referenced in other records. If revisions on this associated record are desired, they can be added to that class.
